### ISSUE TITLE
non-ohdsi youtube videos appearing when sorting by most views

### ISSUE THREAD

**Issue by egillax** [OHDSI/CommunityDashboard#40]
When I sort the youtube videos in the dashboard by most views the top 5 videos seem to be non-ohdsi related:

<html><body>

LIBOG (Full Movie) | 2014-02-26 | PT17M54S | 2230095 | No Mappings Found
-- | -- | -- | -- | --
कुत्ता और उसकी हड्डी (Dog and Bone) - Hindi Kahaniya for Kids \| Stories for Kids \| ChuChu TV Hindi | 2018-10-19 | PT5M28S | 1292727 | No Mappings Found
Hamad Nashwati \| Shakli Hubek \| Ana Taban \| Arabic Song | 2020-10-23 | PT2M31S | 785601 | No Mappings Found
HSC 2nd Year, Math Chapter 3 (জটিল সংখ্যা)  Part - 1 | 2020-04-30 | PT1H1M4S | 41024 | No Mappings Found
Reaction on Bitch I&#39;m Back (Official Audio) - Sidhu Moose Wala | 2021-08-12 | PT5M53S | 22573 | No Mappings Found

</body>

**Comment by natb1** [comment]
ty for logging this, we're looking into this one, we thought maybe OHDSI had just tapped into the Hindi kids segment.

**Comment by natb1** [comment]
thanks again. These particular examples are fixed now. Please feel free to let us know if you see any others, or if you see any trend in the false search results.
